package com.erp.platform.identity.domain;

import com.erp.platform.data.lock.OptimisticLock;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.UuidGenerator;

import java.time.Instant;
import java.util.UUID;

/**
 * Permission aggregate root for fine-grained access control.
 *
 * <p>Represents a business permission in the multi-tenant ERP platform.
 * Permissions define specific actions that can be performed on resources.
 *
 * <p>The aggregate follows Clean Architecture and DDD principles:
 * <ul>
 *   <li>Extends {@link OptimisticLock} for optimistic locking support</li>
 *   <li>Encapsulates all permission business logic and invariants</li>
 *   <li>Does not expose mutable state directly (no setters for business fields)</li>
 *   <li>Provides domain behavior methods for state transitions</li>
 * </ul>
 *
 * <p><strong>Permission Structure:</strong>
 * <ul>
 *   <li>Resource: The business module/domain (e.g., PRODUCT, SALES, INVENTORY)</li>
 *   <li>Action: The operation type (e.g., CREATE, READ, UPDATE, DELETE)</li>
 *   <li>Permission Code: Unique identifier combining resource and action (e.g., PRODUCT_CREATE)</li>
 * </ul>
 *
 * <p><strong>Lifecycle Rules:</strong>
 * <ul>
 *   <li>ACTIVE → INACTIVE (via deactivate)</li>
 *   <li>INACTIVE → ACTIVE (via reactivate)</li>
 * </ul>
 *
 * @since 1.0.0
 */
@Entity
@Table(name = "permissions")
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@Builder(toBuilder = true)
public class Permission extends OptimisticLock<Long> {

    private static final long serialVersionUID = 1L;

    /**
     * The unique business identifier for the permission.
     * Used for API access, external references, and audit trails.
     * This is a UUID (not String) as per requirements.
     */
    @Column(name = "permission_id", nullable = false, unique = true, updatable = false)
    private UUID permissionId;

    /**
     * Unique permission code.
     * Generated by combining resource and action (e.g., "PRODUCT_CREATE").
     * Used for programmatic access, API references, and role assignments.
     * Must be unique across all permissions.
     */
    @Column(name = "permission_code", nullable = false, unique = true, length = 100)
    private String permissionCode;

    /**
     * The business resource this permission applies to.
     * Examples: PRODUCT, SALES, PURCHASE, INVENTORY, HR, ACCOUNTING, CRM, AI
     */
    @Column(name = "resource", nullable = false, length = 50)
    @Enumerated(EnumType.STRING)
    private Resource resource;

    /**
     * The action this permission grants on the resource.
     * Examples: CREATE, READ, UPDATE, DELETE, APPROVE, EXPORT
     */
    @Column(name = "action", nullable = false, length = 50)
    @Enumerated(EnumType.STRING)
    private Action action;

    /**
     * Human-readable description of the permission.
     * Used for documentation, UI display, and audit trails.
     */
    @Column(name = "description", length = 500)
    private String description;

    /**
     * Current status of the permission.
     * Controls whether the permission can be assigned to roles.
     */
    @Column(name = "status", nullable = false, length = 20)
    @Enumerated(EnumType.STRING)
    private PermissionStatus status;

    /**
     * Timestamp when the permission was deactivated.
     * Set when transitioning to INACTIVE status.
     */
    @Column(name = "deactivated_at")
    private Instant deactivatedAt;

    // ==============
    // Factory Methods
    // ==============

    /**
     * Factory method to create a new permission.
     *
     * <p>The application layer is responsible for providing the permissionId.
     * This ensures proper UUID generation at the application layer.
     *
     * <p>The permission code is automatically generated from resource and action.
     *
     * @param permissionId the unique permission identifier (UUID)
     * @param resource the business resource
     * @param action the action type
     * @param description the permission description
     * @return a new Permission instance
     */
    public static Permission create(UUID permissionId, Resource resource, Action action, String description) {
        String permissionCode = generatePermissionCode(resource, action);
        return Permission.builder()
                .permissionId(permissionId)
                .permissionCode(permissionCode)
                .resource(resource)
                .action(action)
                .description(description)
                .status(PermissionStatus.ACTIVE)
                .build();
    }

    // ==============
    // Business Behavior
    // ==============

    /**
     * Deactivates the permission.
     *
     * <p>Transitions the permission from ACTIVE to INACTIVE.
     * Inactive permissions cannot be assigned to new roles,
     * but existing assignments remain for audit purposes.
     *
     * @param deactivatedAt the timestamp when deactivation occurs
     */
    public void deactivate(Instant deactivatedAt) {
        if (this.status == PermissionStatus.INACTIVE) {
            return; // Already inactive
        }
        this.status = PermissionStatus.INACTIVE;
        this.deactivatedAt = deactivatedAt;
    }

    /**
     * Reactivates the permission.
     *
     * <p>Transitions the permission from INACTIVE to ACTIVE.
     * The permission can be assigned to roles again.
     */
    public void reactivate() {
        if (this.status == PermissionStatus.ACTIVE) {
            return; // Already active
        }
        this.status = PermissionStatus.ACTIVE;
        this.deactivatedAt = null;
    }

    /**
     * Updates the permission description.
     *
     * @param description the new description
     */
    public void updateDescription(String description) {
        if (description != null && !description.isBlank()) {
            this.description = description;
        }
    }

    // ==============
    // Query Methods
    // ==============

    /**
     * Generates the permission code from resource and action.
     *
     * <p>Format: {RESOURCE}_{ACTION}
     * Example: PRODUCT_CREATE, SALES_READ, INVENTORY_APPROVE
     *
     * @param resource the business resource
     * @param action the action type
     * @return the generated permission code
     */
    public static String generatePermissionCode(Resource resource, Action action) {
        return resource.name() + "_" + action.name();
    }

    /**
     * Checks if the permission is active.
     *
     * @return true if the permission is active, false otherwise
     */
    public boolean isActive() {
        return this.status == PermissionStatus.ACTIVE;
    }

    /**
     * Checks if the permission is inactive.
     *
     * @return true if the permission is inactive, false otherwise
     */
    public boolean isInactive() {
        return this.status == PermissionStatus.INACTIVE;
    }

    /**
     * Checks if the permission can be assigned to roles.
     *
     * <p>Only active permissions can be assigned.
     *
     * @return true if the permission can be assigned, false otherwise
     */
    public boolean canBeAssigned() {
        return this.status == PermissionStatus.ACTIVE;
    }

    /**
     * Checks if the permission can be deactivated.
     *
     * @return true if the permission can be deactivated, false otherwise
     */
    public boolean canBeDeactivated() {
        return this.status == PermissionStatus.ACTIVE;
    }

    /**
     * Checks if the permission can be reactivated.
     *
     * @return true if the permission can be reactivated, false otherwise
     */
    public boolean canBeReactivated() {
        return this.status == PermissionStatus.INACTIVE;
    }
}
