apiVersion: v1
kind: ConfigMap
metadata:
  name: erpai-config
  namespace: erpai-platform
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_METRICS_TAGS_APPLICATION: "${spring.application.name}"
