package com.erp.platform.identity.application;

import com.erp.platform.identity.application.dto.CreatePermissionRequest;
import com.erp.platform.identity.application.dto.PermissionListResponse;
import com.erp.platform.identity.application.dto.PermissionResponse;
import com.erp.platform.identity.application.dto.UpdatePermissionRequest;
import com.erp.platform.identity.application.mapper.PermissionMapper;
import com.erp.platform.identity.domain.ActionEntity;
import com.erp.platform.identity.domain.Permission;
import com.erp.platform.identity.domain.PermissionStatus;
import com.erp.platform.identity.domain.ResourceMaster;
import com.erp.platform.identity.domain.exception.DuplicatePermissionCodeException;
import com.erp.platform.identity.domain.exception.PermissionNotFoundException;
import com.erp.platform.identity.domain.exception.UnauthorizedException;
import com.erp.platform.identity.infrastructure.persistence.ActionRepository;
import com.erp.platform.identity.infrastructure.persistence.PermissionRepository;
import com.erp.platform.identity.infrastructure.persistence.ResourceMasterRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.List;

/**
 * Service implementation for Permission aggregate operations.
 *
 * @since 1.0.0
 */
@Service
@Transactional(readOnly = true)
public class PermissionServiceImpl implements PermissionService {

    private final PermissionRepository permissionRepository;
    private final ResourceMasterRepository resourceMasterRepository;
    private final ActionRepository actionRepository;
    private final CurrentTenantProvider currentTenantProvider;
    private final AuthorizationService authorizationService;

    public PermissionServiceImpl(PermissionRepository permissionRepository, ResourceMasterRepository resourceMasterRepository, ActionRepository actionRepository, CurrentTenantProvider currentTenantProvider, AuthorizationService authorizationService) {
        this.permissionRepository = permissionRepository;
        this.resourceMasterRepository = resourceMasterRepository;
        this.actionRepository = actionRepository;
        this.currentTenantProvider = currentTenantProvider;
        this.authorizationService = authorizationService;
    }

    @Override
    @Transactional
    public PermissionResponse createPermission(CreatePermissionRequest request) {
        // Only SUPER_ADMIN or TENANT_ADMIN can create permissions
        authorizationService.requireAnyAdmin();

        // Look up resource and action by code
        ResourceMaster resource = resourceMasterRepository.findByResourceCode(request.resourceCode())
                .orElseThrow(() -> new IllegalArgumentException("Resource not found: " + request.resourceCode()));
        ActionEntity action = actionRepository.findByActionCode(request.actionCode())
                .orElseThrow(() -> new IllegalArgumentException("Action not found: " + request.actionCode()));

        // Check for duplicate permission code
        String permissionCode = Permission.generatePermissionCode(resource, action);
        if (permissionRepository.existsByPermissionCode(permissionCode)) {
            throw new DuplicatePermissionCodeException(permissionCode);
        }

        // Create permission using factory method
        Permission permission = Permission.create(
                null, // id - generated by database
                resource,
                action,
                request.resourceCode() + "_" + request.actionCode(),
                request.description()
        );

        Permission savedPermission = permissionRepository.save(permission);
        return PermissionMapper.toResponse(savedPermission);
    }

    @Override
    @Transactional
    public PermissionResponse updatePermission(Long permissionId, UpdatePermissionRequest request) {
        // Only SUPER_ADMIN or TENANT_ADMIN can update permissions
        authorizationService.requireAnyAdmin();

        Permission permission = permissionRepository.findById(permissionId)
                .orElseThrow(() -> PermissionNotFoundException.byId(permissionId));

        permission.updateDescription(request.description());

        Permission updatedPermission = permissionRepository.save(permission);
        return PermissionMapper.toResponse(updatedPermission);
    }

    @Override
    @Transactional
    public void deletePermission(Long permissionId) {
        // Only SUPER_ADMIN or TENANT_ADMIN can delete permissions
        authorizationService.requireAnyAdmin();

        Permission permission = permissionRepository.findById(permissionId)
                .orElseThrow(() -> PermissionNotFoundException.byId(permissionId));

        // Soft delete via deactivation
        permission.deactivate(Instant.now());

        permissionRepository.save(permission);
    }

    @Override
    public PermissionResponse getPermissionById(Long permissionId) {
        Permission permission = permissionRepository.findById(permissionId)
                .orElseThrow(() -> PermissionNotFoundException.byId(permissionId));
        return PermissionMapper.toResponse(permission);
    }

    @Override
    public PermissionResponse getPermissionByCode(String permissionCode) {
        Permission permission = permissionRepository.findByPermissionCode(permissionCode)
                .orElseThrow(() -> PermissionNotFoundException.byPermissionCode(permissionCode));
        return PermissionMapper.toResponse(permission);
    }

    @Override
    public PermissionListResponse listPermissions(String resourceCode, String actionCode, PermissionStatus status, Pageable pageable) {
        Page<Permission> permissionPage;

        if (resourceCode != null && actionCode != null && status != null) {
            ResourceMaster resource = resourceMasterRepository.findByResourceCode(resourceCode)
                    .orElseThrow(() -> new IllegalArgumentException("Resource not found: " + resourceCode));
            permissionPage = permissionRepository.findByResourceCodeAndStatus(resourceCode, status, pageable);
            List<Permission> filteredPermissions = permissionPage.getContent().stream()
                    .filter(permission -> permission.getActionCode().equals(actionCode))
                    .toList();
            return PermissionMapper.toListResponse(PermissionMapper.toResponseList(filteredPermissions),
                    permissionPage.getTotalElements(), permissionPage.getTotalPages(), permissionPage.getNumber(), permissionPage.getSize());
        } else if (resourceCode != null && status != null) {
            ResourceMaster resource = resourceMasterRepository.findByResourceCode(resourceCode)
                    .orElseThrow(() -> new IllegalArgumentException("Resource not found: " + resourceCode));
            permissionPage = permissionRepository.findByResourceCodeAndStatus(resourceCode, status, pageable);
        } else if (resourceCode != null) {
            ResourceMaster resource = resourceMasterRepository.findByResourceCode(resourceCode)
                    .orElseThrow(() -> new IllegalArgumentException("Resource not found: " + resourceCode));
            permissionPage = permissionRepository.findByResourceCode(resourceCode, pageable);
        } else if (actionCode != null) {
            ActionEntity action = actionRepository.findByActionCode(actionCode)
                    .orElseThrow(() -> new IllegalArgumentException("Action not found: " + actionCode));
            permissionPage = permissionRepository.findByActionCode(actionCode, pageable);
        } else if (status != null) {
            permissionPage = permissionRepository.findByStatus(status, pageable);
        } else {
            permissionPage = permissionRepository.findAll(pageable);
        }

        return PermissionMapper.toListResponse(
                PermissionMapper.toResponseList(permissionPage.getContent()),
                permissionPage.getTotalElements(),
                permissionPage.getTotalPages(),
                permissionPage.getNumber(),
                permissionPage.getSize()
        );
    }

    @Override
    public PermissionListResponse listPermissionsByResource(String resourceCode, Pageable pageable) {
        ResourceMaster resource = resourceMasterRepository.findByResourceCode(resourceCode)
                .orElseThrow(() -> new IllegalArgumentException("Resource not found: " + resourceCode));
        Page<Permission> permissionPage = permissionRepository.findByResourceCode(resourceCode, pageable);
        return PermissionMapper.toListResponse(
                PermissionMapper.toResponseList(permissionPage.getContent()),
                permissionPage.getTotalElements(),
                permissionPage.getTotalPages(),
                permissionPage.getNumber(),
                permissionPage.getSize()
        );
    }

    @Override
    public PermissionListResponse listPermissionsByStatus(PermissionStatus status, Pageable pageable) {
        Page<Permission> permissionPage = permissionRepository.findByStatus(status, pageable);
        return PermissionMapper.toListResponse(
                PermissionMapper.toResponseList(permissionPage.getContent()),
                permissionPage.getTotalElements(),
                permissionPage.getTotalPages(),
                permissionPage.getNumber(),
                permissionPage.getSize()
        );
    }

    @Override
    public PermissionListResponse listPermissionsByAction(String actionCode, Pageable pageable) {
        ActionEntity action = actionRepository.findByActionCode(actionCode)
                .orElseThrow(() -> new IllegalArgumentException("Action not found: " + actionCode));
        Page<Permission> permissionPage = permissionRepository.findByActionCode(actionCode, pageable);
        return PermissionMapper.toListResponse(
                PermissionMapper.toResponseList(permissionPage.getContent()),
                permissionPage.getTotalElements(),
                permissionPage.getTotalPages(),
                permissionPage.getNumber(),
                permissionPage.getSize()
        );
    }

    @Override
    public boolean existsByPermissionCode(String permissionCode) {
        return permissionRepository.existsByPermissionCode(permissionCode);
    }

    @Override
    public boolean existsByPermissionId(Long permissionId) {
        return permissionRepository.existsById(permissionId);
    }
}
