-- Migration: V24
-- Description: Normalize the resources table to use a BIGINT identity primary
-- key while preserving rows already present in existing deployments.
--
-- V22 created this table with BIGSERIAL. Flyway migrations are immutable once
-- applied, so this migration safely converts an existing BIGSERIAL column to
-- an identity column and advances the identity sequence to the current maximum
-- ID. New installations receive the identity definition directly.

CREATE TABLE IF NOT EXISTS resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_code VARCHAR(50) NOT NULL,
    resource_name VARCHAR(100) NOT NULL,
    module VARCHAR(50),
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    version BIGINT NOT NULL DEFAULT 0,
    is_system BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT uk_resources_resource_code UNIQUE (resource_code),
    CONSTRAINT chk_resources_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT chk_resources_resource_code_length CHECK (length(resource_code) <= 50),
    CONSTRAINT chk_resources_resource_name_length CHECK (length(resource_name) <= 100),
    CONSTRAINT chk_resources_module_length CHECK (module IS NULL OR length(module) <= 50),
    CONSTRAINT chk_resources_description_length CHECK (description IS NULL OR length(description) <= 500)
);

DO $$
DECLARE
    resource_table regclass := to_regclass('resources');
    id_type text;
    id_identity "char";
    identity_sequence regclass;
    resource_code_attnum smallint;
    max_id bigint;
    sequence_last_value bigint;
    sequence_is_called boolean;
BEGIN
    IF resource_table IS NULL THEN
        RAISE EXCEPTION 'resources table was not created';
    END IF;

    -- Prevent concurrent inserts while the identity sequence is synchronized.
    LOCK TABLE resources IN SHARE ROW EXCLUSIVE MODE;

    SELECT format_type(attribute.atttypid, attribute.atttypmod), attribute.attidentity
      INTO id_type, id_identity
      FROM pg_attribute AS attribute
     WHERE attribute.attrelid = resource_table
       AND attribute.attname = 'id'
       AND attribute.attnum > 0
       AND NOT attribute.attisdropped;

    IF id_type IS NULL THEN
        RAISE EXCEPTION 'resources.id column is missing';
    END IF;

    IF id_type <> 'bigint' THEN
        RAISE EXCEPTION 'resources.id must be BIGINT; found %', id_type;
    END IF;

    -- Convert a legacy BIGSERIAL column, or normalize an existing identity
    -- column to the required BY DEFAULT behavior.
    IF id_identity = '' THEN
        ALTER TABLE resources ALTER COLUMN id DROP DEFAULT;
        ALTER TABLE resources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    ELSIF id_identity <> 'd' THEN
        ALTER TABLE resources ALTER COLUMN id SET GENERATED BY DEFAULT;
    END IF;

    ALTER TABLE resources ALTER COLUMN id SET NOT NULL;

    -- Ensure the required primary key is present without replacing an
    -- existing key on another column.
    IF EXISTS (
        SELECT 1
          FROM pg_constraint AS primary_key
         WHERE primary_key.conrelid = resource_table
           AND primary_key.contype = 'p'
    ) AND NOT EXISTS (
        SELECT 1
          FROM pg_constraint AS primary_key
          CROSS JOIN unnest(primary_key.conkey) AS key_attnum(attnum)
          JOIN pg_attribute AS key_attribute
            ON key_attribute.attrelid = primary_key.conrelid
           AND key_attribute.attnum = key_attnum.attnum
         WHERE primary_key.conrelid = resource_table
           AND primary_key.contype = 'p'
           AND key_attribute.attname = 'id'
    ) THEN
        RAISE EXCEPTION 'resources primary key must be defined on id';
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM pg_constraint AS primary_key
         WHERE primary_key.conrelid = resource_table
           AND primary_key.contype = 'p'
    ) THEN
        ALTER TABLE resources ADD PRIMARY KEY (id);
    END IF;

    -- PostgreSQL creates a new sequence when converting BIGSERIAL to IDENTITY.
    -- Identify that identity-owned sequence rather than the obsolete serial
    -- sequence so existing IDs are never reused.
    SELECT sequence.oid::regclass
      INTO identity_sequence
      FROM pg_class AS sequence
      JOIN pg_depend AS dependency
        ON dependency.objid = sequence.oid
      JOIN pg_attribute AS attribute
        ON attribute.attrelid = dependency.refobjid
       AND attribute.attnum = dependency.refobjsubid
     WHERE dependency.refobjid = resource_table
       AND attribute.attname = 'id'
       AND dependency.deptype = 'i'
       AND sequence.relkind = 'S'
     LIMIT 1;

    SELECT COALESCE(MAX(id), 0) INTO max_id FROM resources;

    IF identity_sequence IS NOT NULL AND max_id > 0 THEN
        EXECUTE format(
            'SELECT last_value, is_called FROM %s',
            identity_sequence::regclass
        )
        INTO sequence_last_value, sequence_is_called;

        IF sequence_last_value IS NULL
           OR max_id > sequence_last_value
           OR (max_id = sequence_last_value AND NOT sequence_is_called)
        THEN
            EXECUTE format(
                'SELECT setval(%L, %s, true)',
                identity_sequence::regclass::text,
                max_id
            );
        END IF;
    END IF;

    -- Keep resource_code unique for both new installations and tables created
    -- by an earlier schema version. Existing unique indexes/constraints are
    -- left intact to avoid unnecessary constraint churn.
    SELECT attribute.attnum
      INTO resource_code_attnum
      FROM pg_attribute AS attribute
     WHERE attribute.attrelid = resource_table
       AND attribute.attname = 'resource_code'
       AND attribute.attnum > 0
       AND NOT attribute.attisdropped;

    IF resource_code_attnum IS NULL THEN
        RAISE EXCEPTION 'resources.resource_code column is missing';
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM pg_index AS index_definition
         WHERE index_definition.indrelid = resource_table
           AND index_definition.indisunique
           AND index_definition.indpred IS NULL
           AND index_definition.indnkeyatts = 1
           AND resource_code_attnum = ANY(index_definition.indkey)
    ) THEN
        ALTER TABLE resources
            ADD CONSTRAINT uk_resources_resource_code UNIQUE (resource_code);
    END IF;

    -- V22 did not contain this model field. Adding it with a default preserves
    -- all existing rows and makes them non-system resources by default.
    ALTER TABLE resources
        ADD COLUMN IF NOT EXISTS is_system BOOLEAN NOT NULL DEFAULT false;

    UPDATE resources
       SET is_system = false
     WHERE is_system IS NULL;

    ALTER TABLE resources
        ALTER COLUMN is_system SET DEFAULT false,
        ALTER COLUMN is_system SET NOT NULL;
END $$;
