-- Migration: V26
-- Description: Creates the actions table and refactors the permissions table
-- to use database-backed Resource (ResourceMaster) and Action references
-- instead of enum-based Resource/Action columns.

-- ============================================================
-- 1. Create the actions table
-- ============================================================
CREATE TABLE IF NOT EXISTS actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_code VARCHAR(50) NOT NULL,
    action_name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    version BIGINT NOT NULL DEFAULT 0,
    is_system BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT uk_actions_action_code UNIQUE (action_code),
    CONSTRAINT chk_actions_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT chk_actions_action_code_length CHECK (length(action_code) <= 50),
    CONSTRAINT chk_actions_action_name_length CHECK (length(action_name) <= 100),
    CONSTRAINT chk_actions_description_length CHECK (description IS NULL OR length(description) <= 500)
);

-- ============================================================
-- 2. Seed initial global actions
-- ============================================================
INSERT INTO actions (action_code, action_name, status, is_system, created_at, version) VALUES
    ('CREATE', 'Create', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('VIEW', 'View', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('UPDATE', 'Update', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('DELETE', 'Delete', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('APPROVE', 'Approve', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('REJECT', 'Reject', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('EXPORT', 'Export', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('IMPORT', 'Import', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('MANAGE', 'Manage', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('ASSIGN', 'Assign', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('CANCEL', 'Cancel', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('REFUND', 'Refund', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('PRINT', 'Print', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('ADJUST', 'Adjust', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('TRANSFER', 'Transfer', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0)
ON CONFLICT (action_code) DO NOTHING;

-- ============================================================
-- 3. Seed legacy permission resources
-- ============================================================
-- V25 seeds the newer business resource vocabulary, while existing
-- deployments may contain permissions for the original Resource enum
-- values. Seed those codes before resolving foreign keys so every legacy
-- permission can be migrated without losing its existing permission_code.
INSERT INTO resources (
    resource_code,
    resource_name,
    module,
    description,
    status,
    is_system,
    created_at,
    version
) VALUES
    ('SALES', 'Sales', 'SALES', 'Sales and order management', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('HR', 'Human Resources', 'HR', 'Human resources management', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('ACCOUNTING', 'Accounting', 'ACCOUNTING', 'Accounting and financial management', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('CRM', 'Customer Relationship Management', 'CRM', 'Customer relationship management', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('AI', 'Artificial Intelligence', 'AI', 'Artificial intelligence capabilities', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('MANUFACTURING', 'Manufacturing', 'MANUFACTURING', 'Manufacturing and production management', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('PLATFORM', 'Platform', 'PLATFORM', 'Platform administration', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('REPORTING', 'Reporting', 'REPORTING', 'Reporting and analytics', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('INTEGRATION', 'Integration', 'INTEGRATION', 'External integrations', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('IDENTITY', 'Identity', 'IDENTITY', 'Identity and access management', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('DEPARTMENT', 'Department', 'IDENTITY', 'Organizational departments', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('PERMISSION', 'Permission', 'IDENTITY', 'Permission definitions', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('USER_ROLE', 'User Role', 'IDENTITY', 'User and role assignments', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('USER_BRANCH', 'User Branch', 'IDENTITY', 'User and branch assignments', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('USER_DEPARTMENT', 'User Department', 'IDENTITY', 'User and department assignments', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('PROVINCE', 'Province', 'IDENTITY', 'Province definitions', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('DISTRICT', 'District', 'IDENTITY', 'District definitions', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('LOCAL_LEVEL', 'Local Level', 'IDENTITY', 'Local level definitions', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0),
    ('RESOURCE', 'Resource', 'IDENTITY', 'Resource master definitions', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, 0)
ON CONFLICT (resource_code) DO NOTHING;

-- ============================================================
-- 4. Refactor permissions table
-- ============================================================

-- Add new columns for database-backed resource and action references
ALTER TABLE permissions
    ADD COLUMN IF NOT EXISTS resource_id BIGINT,
    ADD COLUMN IF NOT EXISTS action_id BIGINT,
    ADD COLUMN IF NOT EXISTS permission_name VARCHAR(200),
    ADD COLUMN IF NOT EXISTS is_system BOOLEAN NOT NULL DEFAULT false;

-- Add foreign key constraints idempotently so an interrupted or manually
-- replayed migration can be retried safely.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM pg_constraint
         WHERE conrelid = 'permissions'::regclass
           AND conname = 'fk_permissions_resource_id'
    ) THEN
        ALTER TABLE permissions
            ADD CONSTRAINT fk_permissions_resource_id
            FOREIGN KEY (resource_id) REFERENCES resources(id)
            ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM pg_constraint
         WHERE conrelid = 'permissions'::regclass
           AND conname = 'fk_permissions_action_id'
    ) THEN
        ALTER TABLE permissions
            ADD CONSTRAINT fk_permissions_action_id
            FOREIGN KEY (action_id) REFERENCES actions(id)
            ON DELETE RESTRICT;
    END IF;
END $$;

-- Migrate existing data: map enum resource/action values to resource/action IDs.
-- Skip this step when a previous attempt already dropped the legacy columns.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM pg_attribute
         WHERE attrelid = 'permissions'::regclass
           AND attname = 'resource'
           AND attnum > 0
           AND NOT attisdropped
    ) AND EXISTS (
        SELECT 1
          FROM pg_attribute
         WHERE attrelid = 'permissions'::regclass
           AND attname = 'action'
           AND attnum > 0
           AND NOT attisdropped
    ) THEN
        UPDATE permissions p
           SET resource_id = r.id,
               action_id = a.id
          FROM resources r, actions a
         WHERE p.resource = r.resource_code
           AND p.action = a.action_code;
    END IF;
END $$;

-- Make new columns non-nullable after data migration
ALTER TABLE permissions
    ALTER COLUMN resource_id SET NOT NULL,
    ALTER COLUMN action_id SET NOT NULL;

-- Drop old enum columns
ALTER TABLE permissions DROP COLUMN IF EXISTS resource;
ALTER TABLE permissions DROP COLUMN IF EXISTS action;

-- Drop old indexes that referenced enum columns
DROP INDEX IF EXISTS idx_permissions_resource;
DROP INDEX IF EXISTS idx_permissions_action;
DROP INDEX IF EXISTS idx_permissions_resource_action;

-- Create new indexes for database-backed references
CREATE INDEX IF NOT EXISTS idx_permissions_resource_id ON permissions(resource_id);
CREATE INDEX IF NOT EXISTS idx_permissions_action_id ON permissions(action_id);
CREATE INDEX IF NOT EXISTS idx_permissions_resource_action ON permissions(resource_id, action_id);
CREATE INDEX IF NOT EXISTS idx_permissions_permission_name ON permissions(permission_name);

-- Update unique constraint on permission_code (keep as is)
-- Update status check constraint (keep as is)

-- ============================================================
-- 4. Drop old permission_id UUID column and its index
-- ============================================================
DROP INDEX IF EXISTS idx_permissions_permission_id;
ALTER TABLE permissions DROP COLUMN IF EXISTS permission_id;
