-- Migration: V27
-- Description: Normalize the permissions table to use a BIGINT identity primary
-- key while preserving rows already present in existing deployments.
-- Also adds unique constraint on (resource_id, action_id).
--
-- V26 created this table with BIGSERIAL. Flyway migrations are immutable once
-- applied, so this migration safely converts an existing BIGSERIAL column to
-- an identity column and advances the identity sequence to the current maximum
-- ID. New installations receive the identity definition directly.

CREATE TABLE IF NOT EXISTS permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code VARCHAR(100) NOT NULL,
    resource_id BIGINT NOT NULL,
    action_id BIGINT NOT NULL,
    permission_name VARCHAR(200),
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    deactivated_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    version BIGINT NOT NULL DEFAULT 0,
    is_system BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT uk_permissions_permission_code UNIQUE (permission_code),
    CONSTRAINT uk_permissions_resource_action UNIQUE (resource_id, action_id),
    CONSTRAINT chk_permissions_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT chk_permissions_permission_code_length CHECK (length(permission_code) <= 100),
    CONSTRAINT chk_permissions_permission_name_length CHECK (permission_name IS NULL OR length(permission_name) <= 200),
    CONSTRAINT chk_permissions_description_length CHECK (description IS NULL OR length(description) <= 500)
);

DO $$
DECLARE
    permission_table regclass := to_regclass('permissions');
    id_type text;
    id_identity "char";
    identity_sequence regclass;
    permission_code_attnum smallint;
    resource_action_attnum smallint[];
    max_id bigint;
    sequence_last_value bigint;
    sequence_is_called boolean;
BEGIN
    IF permission_table IS NULL THEN
        RAISE EXCEPTION 'permissions table was not created';
    END IF;

    -- Prevent concurrent inserts while the identity sequence is synchronized.
    LOCK TABLE permissions IN SHARE ROW EXCLUSIVE MODE;

    SELECT format_type(attribute.atttypid, attribute.atttypmod), attribute.attidentity
      INTO id_type, id_identity
      FROM pg_attribute AS attribute
     WHERE attribute.attrelid = permission_table
       AND attribute.attname = 'id'
       AND attribute.attnum > 0
       AND NOT attribute.attisdropped;

    IF id_type IS NULL THEN
        RAISE EXCEPTION 'permissions.id column is missing';
    END IF;

    IF id_type <> 'bigint' THEN
        RAISE EXCEPTION 'permissions.id must be BIGINT; found %', id_type;
    END IF;

    -- Convert a legacy BIGSERIAL column, or normalize an existing identity
    -- column to the required BY DEFAULT behavior.
    IF id_identity = '' THEN
        ALTER TABLE permissions ALTER COLUMN id DROP DEFAULT;
        ALTER TABLE permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    ELSIF id_identity <> 'd' THEN
        ALTER TABLE permissions ALTER COLUMN id SET GENERATED BY DEFAULT;
    END IF;

    ALTER TABLE permissions ALTER COLUMN id SET NOT NULL;

    -- Ensure the required primary key is present without replacing an
    -- existing key on another column.
    IF EXISTS (
        SELECT 1
          FROM pg_constraint AS primary_key
         WHERE primary_key.conrelid = permission_table
           AND primary_key.contype = 'p'
    ) AND NOT EXISTS (
        SELECT 1
          FROM pg_constraint AS primary_key
          CROSS JOIN unnest(primary_key.conkey) AS key_attnum(attnum)
          JOIN pg_attribute AS key_attribute
            ON key_attribute.attrelid = primary_key.conrelid
           AND key_attribute.attnum = key_attnum.attnum
         WHERE primary_key.conrelid = permission_table
           AND primary_key.contype = 'p'
           AND key_attribute.attname = 'id'
    ) THEN
        RAISE EXCEPTION 'permissions primary key must be defined on id';
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM pg_constraint AS primary_key
         WHERE primary_key.conrelid = permission_table
           AND primary_key.contype = 'p'
    ) THEN
        ALTER TABLE permissions ADD PRIMARY KEY (id);
    END IF;

    -- PostgreSQL creates a new sequence when converting BIGSERIAL to IDENTITY.
    -- Identify that identity-owned sequence rather than the obsolete serial
    -- sequence so existing IDs are never reused.
    SELECT sequence.oid::regclass
      INTO identity_sequence
      FROM pg_class AS sequence
      JOIN pg_depend AS dependency
        ON dependency.objid = sequence.oid
      JOIN pg_attribute AS attribute
        ON attribute.attrelid = dependency.refobjid
       AND attribute.attnum = dependency.refobjsubid
     WHERE dependency.refobjid = permission_table
       AND attribute.attname = 'id'
       AND dependency.deptype = 'i'
       AND sequence.relkind = 'S'
     LIMIT 1;

    SELECT COALESCE(MAX(id), 0) INTO max_id FROM permissions;

    IF identity_sequence IS NOT NULL AND max_id > 0 THEN
        EXECUTE format(
            'SELECT last_value, is_called FROM %s',
            identity_sequence::regclass
        )
        INTO sequence_last_value, sequence_is_called;

        IF sequence_last_value IS NULL
           OR max_id > sequence_last_value
           OR (max_id = sequence_last_value AND NOT sequence_is_called)
        THEN
            EXECUTE format(
                'SELECT setval(%L, %s, true)',
                identity_sequence::regclass::text,
                max_id
            );
        END IF;
    END IF;

    -- Keep permission_code unique for both new installations and tables created
    -- by an earlier schema version. Existing unique indexes/constraints are
    -- left intact to avoid unnecessary constraint churn.
    SELECT attribute.attnum
      INTO permission_code_attnum
      FROM pg_attribute AS attribute
     WHERE attribute.attrelid = permission_table
       AND attribute.attname = 'permission_code'
       AND attribute.attnum > 0
       AND NOT attribute.attisdropped;

    IF permission_code_attnum IS NULL THEN
        RAISE EXCEPTION 'permissions.permission_code column is missing';
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM pg_index AS index_definition
         WHERE index_definition.indrelid = permission_table
           AND index_definition.indisunique
           AND index_definition.indpred IS NULL
           AND index_definition.indnkeyatts = 1
           AND permission_code_attnum = ANY(index_definition.indkey)
    ) THEN
        ALTER TABLE permissions
            ADD CONSTRAINT uk_permissions_permission_code UNIQUE (permission_code);
    END IF;

    -- Add unique constraint on (resource_id, action_id) to prevent duplicate
    -- permissions for the same resource-action combination.
    SELECT ARRAY(
        SELECT attribute.attnum
          FROM pg_attribute AS attribute
         WHERE attribute.attrelid = permission_table
           AND attribute.attname IN ('resource_id', 'action_id')
           AND attribute.attnum > 0
           AND NOT attribute.attisdropped
         ORDER BY attribute.attname
    ) INTO resource_action_attnum;

    IF array_length(resource_action_attnum, 1) <> 2 THEN
        RAISE EXCEPTION 'permissions.resource_id and/or action_id columns are missing';
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM pg_index AS index_definition
         WHERE index_definition.indrelid = permission_table
           AND index_definition.indisunique
           AND index_definition.indpred IS NULL
           AND index_definition.indnkeyatts = 2
           AND resource_action_attnum[1] = ANY(index_definition.indkey)
           AND resource_action_attnum[2] = ANY(index_definition.indkey)
    ) THEN
        ALTER TABLE permissions
            ADD CONSTRAINT uk_permissions_resource_action UNIQUE (resource_id, action_id);
    END IF;

    -- V26 did not contain this model field. Adding it with a default preserves
    -- all existing rows and makes them non-system permissions by default.
    ALTER TABLE permissions
        ADD COLUMN IF NOT EXISTS is_system BOOLEAN NOT NULL DEFAULT false;

    UPDATE permissions
       SET is_system = false
     WHERE is_system IS NULL;

    ALTER TABLE permissions
        ALTER COLUMN is_system SET DEFAULT false,
        ALTER COLUMN is_system SET NOT NULL;

    -- Ensure foreign key constraints exist (idempotent)
    IF NOT EXISTS (
        SELECT 1
          FROM pg_constraint
         WHERE conrelid = permission_table
           AND conname = 'fk_permissions_resource_id'
    ) THEN
        ALTER TABLE permissions
            ADD CONSTRAINT fk_permissions_resource_id
            FOREIGN KEY (resource_id) REFERENCES resources(id)
            ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM pg_constraint
         WHERE conrelid = permission_table
           AND conname = 'fk_permissions_action_id'
    ) THEN
        ALTER TABLE permissions
            ADD CONSTRAINT fk_permissions_action_id
            FOREIGN KEY (action_id) REFERENCES actions(id)
            ON DELETE RESTRICT;
    END IF;

    -- Create indexes for foreign keys if they don't exist
    IF NOT EXISTS (
        SELECT 1
          FROM pg_index
         WHERE indrelid = permission_table
           AND indkey[0] = (
               SELECT attnum
                 FROM pg_attribute
                WHERE attrelid = permission_table
                  AND attname = 'resource_id'
           )
    ) THEN
        CREATE INDEX idx_permissions_resource_id ON permissions(resource_id);
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM pg_index
         WHERE indrelid = permission_table
           AND indkey[0] = (
               SELECT attnum
                 FROM pg_attribute
                WHERE attrelid = permission_table
                  AND attname = 'action_id'
           )
    ) THEN
        CREATE INDEX idx_permissions_action_id ON permissions(action_id);
    END IF;

    -- Create composite index for resource_id, action_id if not exists
    IF NOT EXISTS (
        SELECT 1
          FROM pg_index
         WHERE indrelid = permission_table
           AND indnkeyatts = 2
           AND indkey[0] = (
               SELECT attnum
                 FROM pg_attribute
                WHERE attrelid = permission_table
                  AND attname = 'resource_id'
           )
           AND indkey[1] = (
               SELECT attnum
                 FROM pg_attribute
                WHERE attrelid = permission_table
                  AND attname = 'action_id'
           )
    ) THEN
        CREATE INDEX idx_permissions_resource_action ON permissions(resource_id, action_id);
    END IF;

END $$;
