-- Create role_templates table
-- Migration: V29
-- Description: Creates the role_templates table for global role template definitions.
-- This table stores global, tenant-agnostic role templates that serve as blueprints
-- for provisioning tenant-level roles during onboarding.
-- Role templates are master data shared across all tenants and are therefore
-- not tenant-scoped. They are not directly assigned to users; instead, tenant
-- roles are created from templates and those roles are what get assigned.

CREATE TABLE IF NOT EXISTS role_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_code VARCHAR(100) NOT NULL UNIQUE,
    template_name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    is_system BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    version BIGINT NOT NULL DEFAULT 0,
    -- Constraints
    CONSTRAINT chk_role_templates_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT chk_role_templates_template_code_length CHECK (length(template_code) <= 100),
    CONSTRAINT chk_role_templates_template_name_length CHECK (length(template_name) <= 100),
    CONSTRAINT chk_role_templates_description_length CHECK (description IS NULL OR length(description) <= 500)
);

-- Create indexes for role_templates table
CREATE INDEX idx_role_templates_template_code ON role_templates(template_code);
CREATE INDEX idx_role_templates_template_name ON role_templates(template_name);
CREATE INDEX idx_role_templates_status ON role_templates(status);
CREATE INDEX idx_role_templates_is_system ON role_templates(is_system);
