-- Create the global role-template permission association.
-- Both role_templates and permissions are global aggregates; this table has no tenant_id.

CREATE TABLE IF NOT EXISTS role_template_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    role_template_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    assigned_by VARCHAR(100) NOT NULL,
    assigned_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_role_template_permissions PRIMARY KEY (id),
    CONSTRAINT uk_role_template_permissions_role_permission UNIQUE (role_template_id, permission_id),
    CONSTRAINT fk_role_template_permissions_role_template_id
        FOREIGN KEY (role_template_id) REFERENCES role_templates(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_role_template_permissions_permission_id
        FOREIGN KEY (permission_id) REFERENCES permissions(id)
        ON DELETE CASCADE,
    CONSTRAINT chk_role_template_permissions_assigned_by_length
        CHECK (length(assigned_by) <= 100)
);

CREATE INDEX IF NOT EXISTS idx_role_template_permissions_role_template_id
    ON role_template_permissions(role_template_id);

CREATE INDEX IF NOT EXISTS idx_role_template_permissions_permission_id
    ON role_template_permissions(permission_id);

CREATE INDEX IF NOT EXISTS idx_role_template_permissions_assigned_at
    ON role_template_permissions(assigned_at);
