-- Create tenant-scoped user branch and department assignments.
-- These tables back the UserBranch and UserDepartment association entities.

CREATE TABLE IF NOT EXISTS user_branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_branch_id UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    branch_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    assigned_by VARCHAR(100) NOT NULL,
    assigned_at TIMESTAMP NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(100) NOT NULL,
    updated_by VARCHAR(100) NOT NULL,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_user_branches_tenant_user_branch UNIQUE (tenant_id, user_id, branch_id),
    CONSTRAINT fk_user_branches_user_id_users
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_branches_branch_id_branches
        FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_branches_tenant_id_tenants
        FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT,
    CONSTRAINT chk_user_branches_assigned_by_length
        CHECK (length(assigned_by) <= 100)
);

CREATE INDEX IF NOT EXISTS idx_user_branches_user_id
    ON user_branches(user_id);
CREATE INDEX IF NOT EXISTS idx_user_branches_branch_id
    ON user_branches(branch_id);
CREATE INDEX IF NOT EXISTS idx_user_branches_tenant_id
    ON user_branches(tenant_id);
CREATE INDEX IF NOT EXISTS idx_user_branches_tenant_user
    ON user_branches(tenant_id, user_id);
CREATE INDEX IF NOT EXISTS idx_user_branches_tenant_branch
    ON user_branches(tenant_id, branch_id);
CREATE INDEX IF NOT EXISTS idx_user_branches_assigned_at
    ON user_branches(assigned_at);
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_branches_primary_per_user
    ON user_branches(tenant_id, user_id)
    WHERE is_primary;

CREATE TABLE IF NOT EXISTS user_departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_department_id UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    assigned_by VARCHAR(100) NOT NULL,
    assigned_at TIMESTAMP NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(100) NOT NULL,
    updated_by VARCHAR(100) NOT NULL,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_user_departments_tenant_user_department UNIQUE (tenant_id, user_id, department_id),
    CONSTRAINT fk_user_departments_user_id_users
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_departments_department_id_departments
        FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_departments_tenant_id_tenants
        FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT,
    CONSTRAINT chk_user_departments_assigned_by_length
        CHECK (length(assigned_by) <= 100)
);

CREATE INDEX IF NOT EXISTS idx_user_departments_user_id
    ON user_departments(user_id);
CREATE INDEX IF NOT EXISTS idx_user_departments_department_id
    ON user_departments(department_id);
CREATE INDEX IF NOT EXISTS idx_user_departments_tenant_id
    ON user_departments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_user_departments_tenant_user
    ON user_departments(tenant_id, user_id);
CREATE INDEX IF NOT EXISTS idx_user_departments_tenant_department
    ON user_departments(tenant_id, department_id);
CREATE INDEX IF NOT EXISTS idx_user_departments_assigned_at
    ON user_departments(assigned_at);
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_departments_primary_per_user
    ON user_departments(tenant_id, user_id)
    WHERE is_primary;
